[workspace]
members = ["codegen", "example"]

[package]
name = "asset-bundler"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
edition = "2021"

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
